# Generated by Django 2.0.3 on 2018-04-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('quote', models.CharField(max_length=200)),
                ('artist', models.CharField(default='Unknown', max_length=200)),
                ('producer', models.CharField(default='Unknown', max_length=200)),
                ('genre', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('vocals_body', models.TextField(blank=True, default=None, null=True)),
                ('beat_body', models.TextField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('album_art', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('artist_image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('embed', models.TextField(blank=True, default=None, null=True)),
                ('author', models.CharField(default='Unknown', max_length=200)),
            ],
        ),
    ]
