# Generated by Django 2.0.3 on 2018-03-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embed',
            field=models.TextField(default=''),
        ),
    ]
