# Generated by Django 2.0.3 on 2018-03-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_embed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.AddField(
            model_name='article',
            name='artist',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='beat_body',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='article',
            name='producer',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='vocals_body',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='article',
            name='embed',
            field=models.CharField(default='', max_length=200),
        ),
    ]
