# Generated by Django 2.0.3 on 2018-03-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180320_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='embed',
            field=models.TextField(default=''),
        ),
    ]
