# Generated by Django 2.0.3 on 2018-03-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quote',
            field=models.CharField(default='quote', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='artist',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='producer',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
